version: '3.9'

services:
    web:
        build:
            context: ./Dockerfile
        container_name: web
        ports:
            - '80:3000'
        env_file:
            - .env.production

    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - '27017:27017'
        volumes:
            - mongo-data:/data/db
        environment:
            MONGO_ROOT_USERNAME:
            MONGO_ROOT_PASSWORD:

volumes:
    mongo-data:
